# Generated by Django 5.2.5 on 2025-08-10 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestflow', '0002_assignedip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedip',
            name='assigned_by_admin',
            field=models.BooleanField(default=False, verbose_name='Assigned by Admin'),
        ),
        migrations.AddField(
            model_name='assignedip',
            name='is_monitored',
            field=models.BooleanField(default=False, verbose_name='Monitoring Enabled'),
        ),
        migrations.AlterField(
            model_name='assignedip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignedip',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignedip',
            name='ip_address',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='assignedip',
            name='ip_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_ips', to='requestflow.iprequest'),
        ),
        migrations.AlterField(
            model_name='assignedip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignedip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
