# Generated by Django 5.2.5 on 2025-08-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestflow', '0003_assignedip_assigned_by_admin_assignedip_is_monitored_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'In progress'), ('approved', ' Approved '), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
