# Generated by Django 5.2.5 on 2025-08-06 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='VLAN Name')),
                ('vlan_id', models.PositiveIntegerField(unique=True, verbose_name='VLAN Number')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.CharField(default='other', max_length=100, verbose_name='Category')),
                ('vpn_name', models.CharField(blank=True, max_length=100, verbose_name='VPN Range')),
                ('is_visible_to_users', models.BooleanField(default=False, verbose_name='Visible to Users')),
                ('status', models.BooleanField(default=False, verbose_name='status of vlan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLANs',
                'ordering': ['vlan_id'],
            },
        ),
        migrations.CreateModel(
            name='IPPoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_range_start', models.GenericIPAddressField(protocol='IPv4', verbose_name='Start IP')),
                ('ip_range_end', models.GenericIPAddressField(protocol='IPv4', verbose_name='End IP')),
                ('subnet_mask', models.GenericIPAddressField(protocol='IPv4', verbose_name='Subnet Mask')),
                ('gateway', models.GenericIPAddressField(protocol='IPv4', verbose_name='Gateway')),
                ('dns_servers', models.CharField(blank=True, max_length=255, verbose_name='DNS Servers')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_pools', to='ipm.vlanmodel', verbose_name='VLAN')),
            ],
            options={
                'verbose_name': 'IP Pool',
                'verbose_name_plural': 'IP Pools',
                'ordering': ['ip_range_start'],
            },
        ),
    ]
