# Generated by Django 5.2.5 on 2025-08-06 20:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlanmodel',
            name='category',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Public'), (3, 'Other')], default=1, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='vlanmodel',
            name='vlan_id',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2048)], verbose_name='VLAN Number'),
        ),
    ]
