# Generated by Django 5.2.5 on 2025-08-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipm', '0002_alter_vlanmodel_category_alter_vlanmodel_vlan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlanmodel',
            name='vpn_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='VPN Name'),
        ),
    ]
